//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSFilterHostDll.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSFilterHostDll.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha.
        /// </summary>
        internal static string AlphaChannelName {
            get {
                return ResourceManager.GetString("AlphaChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filter does not support processing completely transparent images..
        /// </summary>
        internal static string BlankDataNotSupported {
            get {
                return ResourceManager.GetString("BlankDataNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string BlueChannelName {
            get {
                return ResourceManager.GetString("BlueChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk full..
        /// </summary>
        internal static string DiskFullError {
            get {
                return ResourceManager.GetString("DiskFullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File I/O error..
        /// </summary>
        internal static string FileIOError {
            get {
                return ResourceManager.GetString("FileIOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File open error..
        /// </summary>
        internal static string FileOpenError {
            get {
                return ResourceManager.GetString("FileOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File read error..
        /// </summary>
        internal static string FileReadError {
            get {
                return ResourceManager.GetString("FileReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File write error..
        /// </summary>
        internal static string FileWriteError {
            get {
                return ResourceManager.GetString("FileWriteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filter does not support {0} images..
        /// </summary>
        internal static string FilterBadModeFormat {
            get {
                return ResourceManager.GetString("FilterBadModeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem with the filter module interface..
        /// </summary>
        internal static string FilterBadParameters {
            get {
                return ResourceManager.GetString("FilterBadParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16-bit Grayscale.
        /// </summary>
        internal static string Gray16Mode {
            get {
                return ResourceManager.GetString("Gray16Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        internal static string GrayChannelName {
            get {
                return ResourceManager.GetString("GrayChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8-bit Grayscale.
        /// </summary>
        internal static string GrayScaleMode {
            get {
                return ResourceManager.GetString("GrayScaleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string GreenChannelName {
            get {
                return ResourceManager.GetString("GreenChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This host does not support colBytes other than 1..
        /// </summary>
        internal static string HostDoesNotSupportColStep {
            get {
                return ResourceManager.GetString("HostDoesNotSupportColStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image height must be less than or equal to 32000 pixels..
        /// </summary>
        internal static string ImageHeightTooLarge {
            get {
                return ResourceManager.GetString("ImageHeightTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size must be less than or equal to 32000x32000 pixels..
        /// </summary>
        internal static string ImageSizeTooLarge {
            get {
                return ResourceManager.GetString("ImageSizeTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image width must be less than or equal to 32000 pixels..
        /// </summary>
        internal static string ImageWidthTooLarge {
            get {
                return ResourceManager.GetString("ImageWidthTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sample point..
        /// </summary>
        internal static string InvalidSamplePoint {
            get {
                return ResourceManager.GetString("InvalidSamplePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Mask.
        /// </summary>
        internal static string MaskChannelName {
            get {
                return ResourceManager.GetString("MaskChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null handle error..
        /// </summary>
        internal static string NullHandleError {
            get {
                return ResourceManager.GetString("NullHandleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of memory..
        /// </summary>
        internal static string OutOfMemoryError {
            get {
                return ResourceManager.GetString("OutOfMemoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the path is denied.
        /// </summary>
        internal static string PathAccessDenied {
            get {
                return ResourceManager.GetString("PathAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string PiMIDefaultCategoryName {
            get {
                return ResourceManager.GetString("PiMIDefaultCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires services not provided by this host..
        /// </summary>
        internal static string PlugInHostInsufficient {
            get {
                return ResourceManager.GetString("PlugInHostInsufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A requested property could not be found..
        /// </summary>
        internal static string PlugInPropertyUndefined {
            get {
                return ResourceManager.GetString("PlugInPropertyUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string RedChannelName {
            get {
                return ResourceManager.GetString("RedChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16-bit RGB.
        /// </summary>
        internal static string RGB48Mode {
            get {
                return ResourceManager.GetString("RGB48Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8-bit RGB.
        /// </summary>
        internal static string RGBMode {
            get {
                return ResourceManager.GetString("RGBMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown channel port..
        /// </summary>
        internal static string UnknownChannelPort {
            get {
                return ResourceManager.GetString("UnknownChannelPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error code: {0}.
        /// </summary>
        internal static string UnknownErrorCodeFormat {
            get {
                return ResourceManager.GetString("UnknownErrorCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported channel bit offset..
        /// </summary>
        internal static string UnsupportedChannelBitOffset {
            get {
                return ResourceManager.GetString("UnsupportedChannelBitOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported channel column bits..
        /// </summary>
        internal static string UnsupportedChannelColumnBits {
            get {
                return ResourceManager.GetString("UnsupportedChannelColumnBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported channel depth..
        /// </summary>
        internal static string UnsupportedChannelDepth {
            get {
                return ResourceManager.GetString("UnsupportedChannelDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported channel depth conversion..
        /// </summary>
        internal static string UnsupportedChannelDepthConversion {
            get {
                return ResourceManager.GetString("UnsupportedChannelDepthConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported channel row bits..
        /// </summary>
        internal static string UnsupportedChannelRowBits {
            get {
                return ResourceManager.GetString("UnsupportedChannelRowBits", resourceCulture);
            }
        }
    }
}
